version: "3.7"
services:
  app_node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: app_smart_house
    container_name: "SMARTHOUSE_HOUSE"
    restart: on-failure
    tty: true
    volumes:
      - ./:/var/www/
    environment:
      SERVICE_NAME: app_smart_house
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "3333:3333"
      - "8999:8999"
    networks:
      - app-network
  postgres: 
    image: postgres:latest
    restart: on-failure
    container_name: "SMARTHOUSE_POSTGRES"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_house
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./docker/database/db_data:/var/lib/postgresql/data
    networks:
      - app-network
  mosquitto: 
    image: eclipse-mosquitto
    restart: on-failure
    container_name: "SMARTHOUSE_MOSQUITTO"
    ports:
      - 1883:1883
      - 8889:8883
    volumes:
       - ./docker/mosquitto/conf:/mosquitto/config
       - ./docker/mosquitto/data:/mosquitto/data
       - ./docker/mosquitto/log:/mosquitto/log
    networks:
      - app-network
  pgadmin4:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: "SMARTHOUSE_PGADMIN"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    volumes:
       - ./docker/database/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
       - ./docker/database/pgpass:/pgpass # passwords for the connections in this file

    ports:
      - "15432:80"
    expose:
      - "15432"
volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge
