name: ci
'on':
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
        # service containers to run with `postgres-job`
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: smart_house
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
    - name: Query database
        run: psql -h postgres -d smart_house -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: password
    - name: "Checkout \U0001F6CE"
      uses: actions/checkout@master
    - name: "Setup node env \U0001F3D7"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '${{ matrix.node }}'
        check-latest: true
    - name: Get yarn cache directory path 🛠
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: "Cache node_modules \U0001F4E6"
      uses: actions/cache@v2.1.4
      id: yarn-cache
      with:
        path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
        key: '${{ runner.os }}-yarn-${{ hashFiles(''**/yarn.lock'') }}'
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Install dependencies \U0001F468\U0001F3FB‍\U0001F4BB"
      run: yarn
    - name: migrations
      run: yarn typeorm migration:run
      env:
        APP_URL: 'http://localhost:3333'
        APP_SECRET_KEY: d2f30b11385709b2b760444be14e2477
        MQTT_HOST: postgres
        MQTT_PORT: 1883
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: smart_house
        DB_TYPE: postgres
    - name: "Run tests \U0001F9EA"
      run: yarn test
      env:
        APP_URL: 'http://localhost:3333'
        APP_SECRET_KEY: d2f30b11385709b2b760444be14e2477
        MQTT_HOST: postgres
        MQTT_PORT: 1883
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: smart_house
        DB_TYPE: postgres
