name: ci
'on':
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: 'postgres:latest'
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: smart_house
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
      mosquitto:
        image: eclipse-mosquitto
        ports:
          - 1883/tcp
          - 8883/tcp
  ci:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 16
    steps:
    - name: "Checkout \U0001F6CE"
      uses: actions/checkout@master
    - name: "Setup node env \U0001F3D7"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '${{ matrix.node }}'
        check-latest: true
    - name: "Get yarn cache directory path \U0001F6E0"
      id: yarn-cache-dir-path
      run: 'echo "::set-output name=dir::$(yarn cache dir)"'
    - name: "Cache node_modules \U0001F4E6"
      uses: actions/cache@v2.1.4
      id: yarn-cache
      with:
        path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
        key: '${{ runner.os }}-yarn-${{ hashFiles(''**/yarn.lock'') }}'
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Install dependencies \U0001F468\U0001F3FB‍\U0001F4BB"
      run: yarn
    
