name: ci
'on':
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: timbru31/ruby-node:latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: "Checkout \U0001F6CE"
      uses: actions/checkout@master
    - name: "Setup node env \U0001F3D7"
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '${{ matrix.node }}'
        check-latest: true
    - name: "Get yarn cache directory path \U0001F6E0"
      id: yarn-cache-dir-path
      run: 'echo "::set-output name=dir::$(yarn cache dir)"'
    - name: "Cache node_modules \U0001F4E6"
      uses: actions/cache@v2.1.4
      id: yarn-cache
      with:
        path: '${{ steps.yarn-cache-dir-path.outputs.dir }}'
        key: '${{ runner.os }}-yarn-${{ hashFiles(''**/yarn.lock'') }}'
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: "Install dependencies \U0001F468\U0001F3FB‍\U0001F4BB"
      run: yarn
    - name: run migrations
      uses: actions/setup-node@v2.1.5
      run: |
        yarn typeorm migration:run
      env:
        APP_URL: 'http://localhost:3333'
        APP_SECRET_KEY: d2f30b11385709b2b760444be14e2477
        MQTT_HOST: postgres
        MQTT_PORT: 1883
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: smart_house
        DB_TYPE: postgres
    - name: "Run tests \U0001F9EA"
      uses: actions/setup-node@v2.1.5
      run: yarn test
      env:
        APP_URL: 'http://localhost:3333'
        APP_SECRET_KEY: d2f30b11385709b2b760444be14e2477
        MQTT_HOST: postgres
        MQTT_PORT: 1883
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_DATABASE: smart_house
        DB_TYPE: postgres
